### ISSUE TITLE
NetBeans 8.1 support

### ISSUE THREAD

**Issue by BKBuEGmbH** [bdamer/drools-netbeans-plugin#1]
I am using NetBeans 8.1. Manually installed the plugin is working, but it is not availabe through the plugin manager, as 8.0 is the last compatible version.

**Comment by markiewb** [comment]
Provide a signed module, let it verify and then it is available for install from the IDE itsself.

See http://wiki.netbeans.org/FaqPluginRequirements or ask

**Comment by bdamer** [comment]
Plugin is currently under verification for both 8.0 and 8.1 - will close this ticket once that is done.

**Comment by bdamer** [comment]
Plugin is now available via plugin manager.
